{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "myapp.fullname" . }}-gateway
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
  {{- with .Values.istio.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  # The selector matches the ingress gateway pod labels.
  # If you installed Istio using Helm following the standard documentation, this would be "istio=ingress"
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.istio.gateway.hosts }}
{{- end }}
---
{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "myapp.fullname" . }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
  {{- with .Values.istio.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hosts:
  - {{ .Values.istio.gateway.hosts }}
  gateways:
  - {{ include "myapp.fullname" . }}-gateway
  http:
  - match:
    - uri:
        prefix: {{ .Values.istio.prefix }}
    route:
    - destination:
        host: {{ include "myapp.fullname" . }}
        port:
          number: {{ .Values.service.port }}
{{- end }}