kind: ConfigMap
apiVersion: v1
metadata:
  name: opa-istio-config
  namespace: {{ .Values.namespace }}
data:
  conf.yaml: |
    discovery:
      name: discovery
      service: styra
    labels:
      system-id: c3199390d3df481099e3a14c900d4dbd
      system-type: template.istio:1.0
    services:
    - name: styra
      url: http://slp-istio-svc:8080/v1
    - name: styra-bundles
      url: http://slp-istio-svc:8080/v1/bundles
