apiVersion: v1
kind: Secret
metadata:
  name: slp-istio
  namespace: {{ .Values.namespace }}
  labels:
    app: slp
    system-type: istio
type: Opaque
stringData:
  slp.yaml: |
    discovery:
      name: discovery
      prefix: /systems/be73004cea78472da407b1630950d432
      service: styra
    labels:
      system-id: be73004cea78472da407b1630950d432
      system-type: template.istio:1.0
    services:
    - credentials:
        bearer:
          token: SY9ygbSYJDyzXRDaaXZX6f0Cs3fS9M4BiriLfwQMQ-YgGVtSkvNFUQy3An0WxBXzoaZccJuVQK_w3TjwHniCMk-hnzdXTWrS
      name: styra
      url: https://br99vz.svc.styra.com/v1
    - credentials:
        bearer:
          token: SY9ygbSYJDyzXRDaaXZX6f0Cs3fS9M4BiriLfwQMQ-YgGVtSkvNFUQy3An0WxBXzoaZccJuVQK_w3TjwHniCMk-hnzdXTWrS
      name: styra-bundles
      url: https://br99vz.svc.styra.com/v1/bundles

---
apiVersion: v1
kind: Service
metadata:
  name: slp-istio-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: slp
    system-type: istio
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: slp
    system-type: istio

---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: slp-istio-app
  namespace: {{ .Values.namespace }}
  labels:
    app: slp
    sytem-type: istio
spec:
  replicas: 1
  serviceName: "slp-istio-app"
  selector:
    matchLabels:
      app: slp
      system-type: istio
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "false"
        app: slp
        system-type: istio
    spec:
      containers:
      - name: slp
        image: "styra/styra-local-plane:0.7.2"
        args:
          - "--config-file=/config/slp.yaml"
          - "--addr=0.0.0.0:8080"
        env:
          - name: SIGSTORE_NO_CACHE
            value: "true"
        livenessProbe:
          httpGet:
            path: /v1/system/alive
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /v1/system/ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: slp-config-vol
          readOnly: true
          mountPath: /config/slp.yaml
          subPath: slp.yaml
        - name: slp-scratch-vol
          mountPath: /scratch
      volumes:
      - name: slp-config-vol
        secret:
          secretName: slp-istio
  volumeClaimTemplates:
  - metadata:
      name: slp-scratch-vol
      namespace: {{ .Values.namespace }}
      labels:
        slp-pvc: slp-istio-app-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
