@MrJB.OPA.StyraDas.API_HostAddress = http://localhost:5069

GET {{MrJB.OPA.StyraDas.API_HostAddress}}/api/security/grid
Accept: application/json

###

GET {{MrJB.OPA.StyraDas.API_HostAddress}}/api/system/test
Accept: application/json

###

GET {{MrJB.OPA.StyraDas.API_HostAddress}}/api/up
Accept: application/json

###
